- name: Erase current worlds if delete_world == true
  ansible.builtin.file:
    state: absent
    path: /minecraft-data/{{ item }}
  loop: 
    - world
    - world_nether
    - world_the_end
  when: delete_world == true

- name: Run Docker-Compose Minecraft Server
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: minecraft-server
    image: itzg/minecraft-server
    published_ports: "{{ minecraft_port }}:25565"
    volumes: /minecraft-data:/data
    restart_policy: always
    env:
#      FORCE_WORLD_COPY: "{{ force_world_copy }}"
      VERSION: "{{ minecraft_version }}"
      TYPE: "{{ server_type }}"
      MEMORY: "{{ memory_capacity }}"
      MOTD: "{{ motd_message }}"
      DIFFICULTY: "{{ game_difficulty }}"
      OPS: "{{ op_user_list }}"
      MAX_PLAYERS: "{{ max_players }}"
      ALLOW_NETHER: "{{ allow_nether }}"
      MAX_WORLD_SIZE: "{{ max_world_size }}"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "{{ announce_player_achievements }}"
      ENABLE_COMMAND_BLOCK: "{{ enable_command_block }}"
      VIEW_DISTANCE: "{{ view_distance }}"
      SEED: "{{ world_seed }}"
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "{{ override_server_properties }}"
#      SKIP_SERVER_PROPERTIES: "{{ skip_server_properties }}"
    tty: true
