- name: Erase current worlds if delete_world == true
  ansible.builtin.file:
    state: absent
    path: /minecraft-data/{{ item }}
  loop: 
    - world
    - world_nether
    - world_the_end
  when: delete_world == true

- name: Run Docker-Compose Minecraft Server
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: minecraft-server
    image: itzg/minecraft-server
    published_ports: "{{ minecraft_port }}:25565"
    volumes: /minecraft-data:/data
    restart_policy: always
    env:
      EULA: "TRUE"
      MEMORY: "{{ memory_capacity }}"
      VERSION: "{{ minecraft_version }}"
      TYPE: "{{ server_type }}"
      MOTD: "{{ motd_message }}"
      SEED: "{{ world_seed }}"
      LEVEL_TYPE: "{{ level_type }}"
      MODE: "{{ gamemode }}"
      DIFFICULTY: "{{ game_difficulty }}"
      PVP: "{{ pvp_enabled }}"
      OPS: "{{ op_user_list }}"
      ALLOW_NETHER: "{{ allow_nether }}"
      MAX_PLAYERS: "{{ max_players }}"
      MAX_WORLD_SIZE: "{{ max_world_size }}"
      MAX_BUILD_HEIGHT: "{{ max_build_height }}"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "{{ announce_player_achievements }}"
      ENABLE_COMMAND_BLOCK: "{{ enable_command_block }}"
      VIEW_DISTANCE: "{{ view_distance }}"
      SPAWN_ANIMALS: "{{ spawn_animals }}"
      SPAWN_MONSTERS: "{{ spawn_monsters }}"
      SPAWN_NPCS: "{{ spawn_npcs }}"
      SPAWN_PROTECTION: "{{ spawn_protection }}"
      OVERRIDE_SERVER_PROPERTIES: "{{ override_server_properties }}"
      FORCE_GAMEMODE: "{{ force_gamemode }}"
      GENERATE_STRUCTURES: "{{ generate_structures }}"
#      FORCE_WORLD_COPY: "{{ force_world_copy }}"
#      SKIP_SERVER_PROPERTIES: "{{ skip_server_properties }}"
    tty: true
