# Make a user which will manage with backups
- name: Make user backup
  ansible.builtin.user:
    name: backup
    createhome: yes
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes

# ansible.posix.mount module - ansible-galaxy collection install ansible.posix
- name: Mount backup USB drive
  ansible.posix.mount:
    path: "{{ ext_backup_dir }}"
    state: mounted
    src: LABEL="{{ backup_usb_label }}"
#   src: UUID="{{ backup_usb_uuid }}"
#   src: "{{ backup_usb_path }}"
    fstype: "{{ backup_usb_fstype }}"
