# There will be a special user for logging/ monitoring services.
## Creating such user
- name: Make user monitoring
  ansible.builtin.user:
    name: monitoring
    groups: docker, video

# CPU Temprature Logging
## Copy teamprature monitoring script
- name: Copy temp-mon.sh script to the server
  ansible.builtin.template:
    src: temp-mon.sh.j2
    dest: /home/monitoring/temp-mon.sh
    owner: monitoring
    mode: '0700'
  no_log: true

## Make cron file that will call temprature monitoring every 3 minutes
- name: Create cron file temp-monitoring script
  ansible.builtin.copy:
    src: temp-mon.cron
    dest: /etc/cron.d/temp-mon

# Server Name Logging
## Since I am using a free Ngrok API, the server name is always a random and sometime it changes
## For that reason I am going to log the current name and in case it changed, the Telegram bot will send a message to my group.
## First we need to install jq, to work with received json data from localhost:4040 (ngrok status page).
- name: Install jq package
  ansible.builtin.apt:
    name: jq

## Copy domain notifier script
- name: Copy domain-notifier.sh script to the server
  ansible.builtin.template:
    src: ngrok-mon.sh.j2
    dest: /home/monitoring/ngrok-mon.sh
    owner: monitoring
    mode: '0700'
  no_log: true

## Make cron file that will call monitoring of ngrok domain name every 5 minutes
- name: Create cron file domain-notifier script
  ansible.builtin.copy:
    src: ngrok-mon.cron
    dest: /etc/cron.d/ngrok-mon
