# Docker install
- name: Install Docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Docker service start
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

# Docker compose
## Check version
#- name: Check current docker-compose version
#  command: docker-compose --version
#  register: docker_compose_vsn
#  changed_when: false
#  failed_when: false
#  check_mode: no
#
#- set_fact:
#    docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
#  when:
#    - docker_compose_vsn.stdout is defined

## Install or upgrade docker-compose
#- name: Install or upgrade docker-compose
#  get_url: 
#    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
#    dest: /usr/local/bin/docker-compose
#    mode: 'a+x'
#    force: yes
#  when: >
#    docker_compose_current_version is not defined
#    or docker_compose_current_version is version(docker_compose_version, '<')
#
