# Docker install
- name: Install Docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Docker service start
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
